shared-version = true
consolidate-commits = true
pre-release-hook = ["sh", "-c", "cd \"$WORKSPACE_ROOT\" && grep -q \"\\[$1\\]\" CHANGELOG.md || git cliff --prepend CHANGELOG.md -u --tag \"$1\"", "sh", "{{version}}"]
publish = false
